USE [master]
ALTER DATABASE [CRM] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [CRM] FROM  DISK = N'C:\Temp\CRM.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [CRM] SET MULTI_USER

GO
