//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminProfile
    {
        public AdminProfile()
        {
            this.AdminConsoleSettings = new HashSet<AdminConsoleSetting>();
            this.AdminRoles = new HashSet<AdminRole>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string AdminConsoleVersion { get; set; }
    
        public virtual ICollection<AdminConsoleSetting> AdminConsoleSettings { get; set; }
        public virtual ICollection<AdminRole> AdminRoles { get; set; }
    }
}
