//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminConsoleSetting
    {
        public int AdminProfileID { get; set; }
        public string View { get; set; }
        public string Control { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
        public string ValueHash { get; set; }
    
        public virtual AdminProfile AdminProfile { get; set; }
    }
}
