//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDetail
    {
        public int ID { get; set; }
        public int AppointmentID { get; set; }
        public int StaffID { get; set; }
        public int ServiceID { get; set; }
        public decimal Price { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
