//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.FinancialTransactions = new HashSet<FinancialTransaction>();
            this.AppointmentDetails = new HashSet<AppointmentDetail>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Price { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal Discount { get; set; }
        public decimal ToPay { get; set; }
        public int StateID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual User CreatedByUser { get; set; }
        public virtual User ModifiedByUser { get; set; }
        public virtual AppointmentState AppointmentState { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; }
    }
}
