//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentView
    {
        public int AppointmentID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Price { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal Discount { get; set; }
        public decimal ToPay { get; set; }
        public Nullable<decimal> Payed { get; set; }
        public int StateID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerMiddleName { get; set; }
        public string DiscountCardCode { get; set; }
        public Nullable<decimal> DiscountCardPercent { get; set; }
        public Nullable<decimal> DiscountCardTotalPurchaseValue { get; set; }
        public Nullable<decimal> DiscountCardMinDiscount { get; set; }
        public Nullable<decimal> DiscountCardMaxDiscount { get; set; }
        public string AppointementDetails { get; set; }
    }
}
