//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockContent
    {
        public int ID { get; set; }
        public int BlockID { get; set; }
        public string Culture { get; set; }
        public string Content { get; set; }
        public System.DateTime StartTime { get; set; }
        public bool IsDraft { get; set; }
        public System.DateTime ContentModificationTime { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Language Language { get; set; }
    }
}
