//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public Block()
        {
            this.BlockContents = new HashSet<BlockContent>();
            this.ElementBlocks = new HashSet<ElementBlock>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WidgetID { get; set; }
        public string Name { get; set; }
        public string DefaultContent { get; set; }
        public string ScriptBlock { get; set; }
        public System.DateTime DefaultContentModificationTime { get; set; }
    
        public virtual Widget Widget { get; set; }
        public virtual ICollection<BlockContent> BlockContents { get; set; }
        public virtual ICollection<ElementBlock> ElementBlocks { get; set; }
    }
}
