//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bot
    {
        public int ID { get; set; }
        public long TradingAccount { get; set; }
        public int TradingAccountType { get; set; }
        public int IntervalMin { get; set; }
        public int IntervalMax { get; set; }
        public int OpenChancePercent { get; set; }
        public int PositivePercent { get; set; }
        public int BorderPercent { get; set; }
        public int MinOrderLive { get; set; }
        public int MaxOrderLive { get; set; }
        public double MaxProfit { get; set; }
        public double MaxVolume { get; set; }
        public string Symbols { get; set; }
        public int TradePeriodFrom { get; set; }
        public int TradePeriodTo { get; set; }
        public int IsActive { get; set; }
    }
}
