//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientExtension
    {
        public int Attribute { get; set; }
        public int ClientID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public System.DateTime Time { get; set; }
        public string StringValue { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
