//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFile
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public string OriginalFileName { get; set; }
        public string Comment { get; set; }
        public string InternalComment { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime UploadTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
