//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Votes = new HashSet<Vote>();
            this.ClientExtensions = new HashSet<ClientExtension>();
            this.ClientFiles = new HashSet<ClientFile>();
            this.ClientIPHistories = new HashSet<ClientIPHistory>();
            this.FinancialTransactions = new HashSet<FinancialTransaction>();
            this.MT4Account = new HashSet<MT4Account>();
            this.TradableAccounts = new HashSet<TradableAccount>();
        }
    
        public int ID { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> ReferrerClientID { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public string InternalComment { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string EmailVerificationCode { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string SystemComment { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime RegistrationTime { get; set; }
    
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<ClientExtension> ClientExtensions { get; set; }
        public virtual ICollection<ClientFile> ClientFiles { get; set; }
        public virtual ICollection<ClientIPHistory> ClientIPHistories { get; set; }
        public virtual ICollection<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual ICollection<MT4Account> MT4Account { get; set; }
        public virtual ICollection<TradableAccount> TradableAccounts { get; set; }
    }
}
