//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAward
    {
        public CompanyAward()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int AwardID { get; set; }
        public int FakeVotes { get; set; }
        public bool IsActive { get; set; }
        public int RealVoices { get; set; }
    
        public virtual Award1 Award { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
