//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyAwards = new HashSet<CompanyAward>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string TypeOfBroker { get; set; }
        public string MinDeposit { get; set; }
        public string PaymentSystem { get; set; }
        public string MaxLeverage { get; set; }
        public string RefLink { get; set; }
        public bool InBrokerPage { get; set; }
    
        public virtual ICollection<CompanyAward> CompanyAwards { get; set; }
    }
}
