//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestOrderLog
    {
        public long ID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Note { get; set; }
    
        public virtual ContestOrder ContestOrder { get; set; }
    }
}
