//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestAccount
    {
        public ContestAccount()
        {
            this.ContestAccountLogs = new HashSet<ContestAccountLog>();
            this.ContestOrders = new HashSet<ContestOrder>();
        }
    
        public long ID { get; set; }
        public int ContestID { get; set; }
        public Nullable<int> MT4AccountID { get; set; }
        public int State { get; set; }
        public decimal Result { get; set; }
        public System.DateTime ParticipationTime { get; set; }
        public int Place { get; set; }
        public System.DateTime LastCalculationTime { get; set; }
        public string InternalComment { get; set; }
        public Nullable<decimal> BalanceOnContestStart { get; set; }
        public string SystemComment { get; set; }
        public Nullable<int> TradableAccountID { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public int ResultPips { get; set; }
    
        public virtual Contest Contest { get; set; }
        public virtual MT4Account MT4Account { get; set; }
        public virtual TradableAccount TradableAccount { get; set; }
        public virtual ICollection<ContestAccountLog> ContestAccountLogs { get; set; }
        public virtual ICollection<ContestOrder> ContestOrders { get; set; }
    }
}
