//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContestOrder
    {
        public ContestOrder()
        {
            this.ContestOrderLogs = new HashSet<ContestOrderLog>();
        }
    
        public long ID { get; set; }
        public long ContestAccountID { get; set; }
        public int OriginalOrderNumber { get; set; }
        public System.DateTime OpenTime { get; set; }
        public decimal OpenPrice { get; set; }
        public bool IsOpenPriceOriginal { get; set; }
        public System.DateTime CloseTime { get; set; }
        public decimal ClosePrice { get; set; }
        public bool IsClosePriceOriginal { get; set; }
        public decimal Profit { get; set; }
        public decimal Swap { get; set; }
        public decimal Commission { get; set; }
        public int SymbolID { get; set; }
        public Nullable<int> Cmd { get; set; }
        public string Result { get; set; }
        public Nullable<int> Command { get; set; }
        public bool IsEditedByAdmin { get; set; }
        public string ResultPips { get; set; }
    
        public virtual ContestAccount ContestAccount { get; set; }
        public virtual Symbol Symbol { get; set; }
        public virtual ICollection<ContestOrderLog> ContestOrderLogs { get; set; }
    }
}
