//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AppointmentState> AppointmentStates { get; set; }
        public virtual DbSet<CumulativeDiscount> CumulativeDiscounts { get; set; }
        public virtual DbSet<DiscountType> DiscountTypes { get; set; }
        public virtual DbSet<PrivelegeGroup> PrivelegeGroups { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DiscountCard> DiscountCards { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Award1> Award1 { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyAward> CompanyAwards { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Bot> Bots { get; set; }
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<BlockContent> BlockContents { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<ElementBlock> ElementBlocks { get; set; }
        public virtual DbSet<ElementParameter> ElementParameters { get; set; }
        public virtual DbSet<ElementWidget> ElementWidgets { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Layout> Layouts { get; set; }
        public virtual DbSet<Widget> Widgets { get; set; }
        public virtual DbSet<AdminConsoleSetting> AdminConsoleSettings { get; set; }
        public virtual DbSet<AdminProfile> AdminProfiles { get; set; }
        public virtual DbSet<AdminRole> AdminRoles { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientExtension> ClientExtensions { get; set; }
        public virtual DbSet<ClientFile> ClientFiles { get; set; }
        public virtual DbSet<ClientIPHistory> ClientIPHistories { get; set; }
        public virtual DbSet<Contest> Contests { get; set; }
        public virtual DbSet<ContestAccount> ContestAccounts { get; set; }
        public virtual DbSet<ContestAccountLog> ContestAccountLogs { get; set; }
        public virtual DbSet<ContestOrder> ContestOrders { get; set; }
        public virtual DbSet<ContestOrderLog> ContestOrderLogs { get; set; }
        public virtual DbSet<ContestPrice> ContestPrices { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dictionary> Dictionaries { get; set; }
        public virtual DbSet<DictionaryHeader> DictionaryHeaders { get; set; }
        public virtual DbSet<FinancialTransaction> FinancialTransactions { get; set; }
        public virtual DbSet<MT4Account> MT4Account { get; set; }
        public virtual DbSet<MT4Server> MT4Server { get; set; }
        public virtual DbSet<PaymentSystemResponse> PaymentSystemResponses { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<RawOrder> RawOrders { get; set; }
        public virtual DbSet<Symbol> Symbols { get; set; }
        public virtual DbSet<TradableAccount> TradableAccounts { get; set; }
        public virtual DbSet<TradablePosition> TradablePositions { get; set; }
        public virtual DbSet<TradableOrder> TradableOrders { get; set; }
        public virtual DbSet<TradablePosition1> TradablePosition1 { get; set; }
    }
}
