//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulativeDiscount
    {
        public int ID { get; set; }
        public decimal Percent { get; set; }
        public decimal MinDiscount { get; set; }
        public decimal MaxDiscount { get; set; }
        public decimal PurchaseTopLimit { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime PurchaseStartTime { get; set; }
        public System.DateTime PurchaseEndTime { get; set; }
    }
}
