//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public int ID { get; set; }
        public int DictionaryNumber { get; set; }
        public string StringValue { get; set; }
        public string Description { get; set; }
    
        public virtual DictionaryHeader DictionaryHeader { get; set; }
    }
}
