//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryHeader
    {
        public DictionaryHeader()
        {
            this.Dictionaries = new HashSet<Dictionary>();
        }
    
        public int Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsFlags { get; set; }
    
        public virtual ICollection<Dictionary> Dictionaries { get; set; }
    }
}
