//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementWidget
    {
        public int ElementID { get; set; }
        public int WidgetID { get; set; }
        public int SortIndex { get; set; }
    
        public virtual Element Element { get; set; }
        public virtual Widget Widget { get; set; }
    }
}
