//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.Element1 = new HashSet<Element>();
            this.ElementBlocks = new HashSet<ElementBlock>();
            this.ElementParameters = new HashSet<ElementParameter>();
            this.ElementWidgets = new HashSet<ElementWidget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentElementID { get; set; }
        public bool IsActive { get; set; }
        public int LayoutID { get; set; }
        public string Url { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Parameters { get; set; }
        public Nullable<int> UrlType { get; set; }
        public int SortIndex { get; set; }
        public int SiteID { get; set; }
    
        public virtual Layout Layout { get; set; }
        public virtual ICollection<Element> Element1 { get; set; }
        public virtual Element Element2 { get; set; }
        public virtual ICollection<ElementBlock> ElementBlocks { get; set; }
        public virtual ICollection<ElementParameter> ElementParameters { get; set; }
        public virtual ICollection<ElementWidget> ElementWidgets { get; set; }
    }
}
