//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransaction
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public int TransactionTypeID { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreationTIme { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModificationTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual User CreatedByUser { get; set; }
        public virtual User ModifiedByUser { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
