//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTransaction
    {
        public FinancialTransaction()
        {
            this.PaymentSystemResponses = new HashSet<PaymentSystemResponse>();
        }
    
        public long ID { get; set; }
        public int ClientID { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public decimal Amount { get; set; }
        public int Initiator { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int Unit { get; set; }
        public Nullable<int> ContestID { get; set; }
        public string VisibleComment { get; set; }
        public string InternalComment { get; set; }
        public Nullable<System.DateTime> StateChangedTime { get; set; }
        public Nullable<int> PaymentSystem { get; set; }
        public string RecipientPSAccountNumber { get; set; }
        public string RecipientPSUniqueID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Contest Contest { get; set; }
        public virtual ICollection<PaymentSystemResponse> PaymentSystemResponses { get; set; }
    }
}
