//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.BlockContents = new HashSet<BlockContent>();
        }
    
        public string Culture { get; set; }
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BlockContent> BlockContents { get; set; }
    }
}
