//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layout
    {
        public Layout()
        {
            this.Elements = new HashSet<Element>();
            this.Widgets = new HashSet<Widget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ElementType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Element> Elements { get; set; }
        public virtual ICollection<Widget> Widgets { get; set; }
    }
}
