//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT4Account
    {
        public MT4Account()
        {
            this.ContestAccounts = new HashSet<ContestAccount>();
            this.RawOrders = new HashSet<RawOrder>();
        }
    
        public int ID { get; set; }
        public int MT4ServerID { get; set; }
        public int ClientID { get; set; }
        public int State { get; set; }
        public string Alias { get; set; }
        public int Login { get; set; }
        public string InvestorPassword { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public Nullable<System.DateTime> LastOrderDownloadTime { get; set; }
        public bool IsDemo { get; set; }
        public decimal BalanceOnLastDownload { get; set; }
        public string SystemComment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ContestAccount> ContestAccounts { get; set; }
        public virtual MT4Server MT4Server { get; set; }
        public virtual ICollection<RawOrder> RawOrders { get; set; }
    }
}
