//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT4Server
    {
        public MT4Server()
        {
            this.MT4Account = new HashSet<MT4Account>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
        public string Address { get; set; }
        public Nullable<int> Port { get; set; }
        public string InternalComment { get; set; }
        public bool IsTelnetEnabled { get; set; }
        public Nullable<bool> IsDemo { get; set; }
        public string DNSAddress { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> UTCTimeOffset { get; set; }
    
        public virtual ICollection<MT4Account> MT4Account { get; set; }
    }
}
