//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSystemResponse
    {
        public long FinancialTransactionID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public decimal Amount { get; set; }
        public int Result { get; set; }
        public string ExtensionParameters { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual FinancialTransaction FinancialTransaction { get; set; }
    }
}
