//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int SymbolID { get; set; }
        public System.DateTime Time { get; set; }
        public decimal Bid { get; set; }
        public decimal Ask { get; set; }
        public string SystemComment { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Symbol Symbol { get; set; }
    }
}
