//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawOrder
    {
        public long ID { get; set; }
        public int MT4AccountID { get; set; }
        public int OrderNumber { get; set; }
        public decimal Volume { get; set; }
        public int Command { get; set; }
        public System.DateTime OpenTime { get; set; }
        public decimal OpenPrice { get; set; }
        public System.DateTime CloseTime { get; set; }
        public decimal ClosePrice { get; set; }
        public string Symbol { get; set; }
        public decimal Profit { get; set; }
        public decimal Swap { get; set; }
        public decimal Commission { get; set; }
    
        public virtual MT4Account MT4Account { get; set; }
    }
}
