//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradableOrder
    {
        public int ID { get; set; }
        public int InstrumentID { get; set; }
        public string InstrumentSymbol { get; set; }
        public string OrderType { get; set; }
        public decimal Quantity { get; set; }
        public decimal FilledQnty { get; set; }
        public Nullable<decimal> AvgFilledPrice { get; set; }
        public System.DateTime CreationTime { get; set; }
        public decimal CurrentBalance { get; set; }
        public int AccountID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> ClientID { get; set; }
    }
}
