//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradableAccount
    {
        public TradableAccount()
        {
            this.ContestAccounts = new HashSet<ContestAccount>();
            this.TradablePositions = new HashSet<TradablePosition>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool IsDemo { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> LastOrderDownloadTime { get; set; }
        public Nullable<decimal> BalanceOnLastDownload { get; set; }
        public string SystemComment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ContestAccount> ContestAccounts { get; set; }
        public virtual ICollection<TradablePosition> TradablePositions { get; set; }
    }
}
