//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int ID { get; set; }
        public int CompanyAwardID { get; set; }
        public string Email { get; set; }
        public string IP { get; set; }
        public string GuidKey { get; set; }
        public bool WasApproved { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
    
        public virtual CompanyAward CompanyAward { get; set; }
        public virtual Client Client { get; set; }
    }
}
