//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySmileCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public Widget()
        {
            this.Blocks = new HashSet<Block>();
            this.ElementWidgets = new HashSet<ElementWidget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LayoutID { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<Block> Blocks { get; set; }
        public virtual ICollection<ElementWidget> ElementWidgets { get; set; }
        public virtual Layout Layout { get; set; }
    }
}
